# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dol.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QStyleFactory


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(996, 405)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setGeometry(QtCore.QRect(20, 60, 961, 291))
wewqe
23455333
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setBackground(QtGui.QColor(88, 88, 88))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(88, 88, 88))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(88, 88, 88))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(88, 88, 88))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(88, 88, 88))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(88, 88, 88))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setItem(0, 0, item)
        self.table.horizontalHeader().setCascadingSectionResizes(True)
        self.table.horizontalHeader().setDefaultSectionSize(100)
        self.table.horizontalHeader().setHighlightSections(True)
        self.table.horizontalHeader().setSortIndicatorShown(False)
        self.table.horizontalHeader().setStretchLastSection(False)
        self.table.verticalHeader().setVisible(True)
        self.btn_change_excel = QtWidgets.QPushButton(self.centralwidget)
        self.btn_change_excel.setGeometry(QtCore.QRect(660, 20, 161, 31))
        self.btn_change_excel.setObjectName("btn_change_excel")
        self.btn_change_html = QtWidgets.QPushButton(self.centralwidget)
        self.btn_change_html.setGeometry(QtCore.QRect(830, 20, 151, 31))
        self.btn_change_html.setObjectName("btn_change_html")
        self.btn_paste = QtWidgets.QPushButton(self.centralwidget)
        self.btn_paste.setGeometry(QtCore.QRect(20, 20, 111, 31))
        self.btn_paste.setObjectName("btn_paste")
        self.btn_paste_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_paste_2.setGeometry(QtCore.QRect(140, 20, 111, 31))
        self.btn_paste_2.setObjectName("btn_paste_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 996, 21))
        self.menubar.setObjectName("menubar")
        self.menuprogram = QtWidgets.QMenu(self.menubar)
        self.menuprogram.setObjectName("menuprogram")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.menuprogram.addAction(self.action_3)
        self.menubar.addAction(self.menuprogram.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "돌보미 명"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "활동 시작"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "활동 종료"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "이용자"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "아동명"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "요일"))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "이용시간"))
        __sortingEnabled = self.table.isSortingEnabled()
        self.table.setSortingEnabled(False)
        self.table.setSortingEnabled(__sortingEnabled)
        self.btn_change_excel.setText(_translate("MainWindow", "EXCEL 변환"))
        self.btn_change_html.setText(_translate("MainWindow", "INTERNET 열기"))
        self.btn_paste.setText(_translate("MainWindow", "데이터 넣기"))
        self.btn_paste_2.setText(_translate("MainWindow", "테이블 적용"))
        self.menuprogram.setTitle(_translate("MainWindow", "도움"))
        self.action_3.setText(_translate("MainWindow", "설명서"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle(QStyleFactory.create('Fusion'))
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
